print(math.sqrt(4))

print(math.abs(4))
print(math.acos(0.2))
print(math.asin(0.2))
print(math.atan(0.2))
print(math.ceil(4))
print(math.cos(4))
print(math.exp(4))
print(math.floor(4))
print(math.log(4))
print(math.log10(4))
print(math.max(1,2,3,4,5))
print(math.min(1,2,3,4,5))
print(math.pow(2, 4))
print(math.sin(4))
print(math.sqrt(4))
print(math.tan(4))